config/routes.rb
Rails.application.routes.draw do

  resources :loans
  resources :quotes
  resources :customers
  resources :salespeople
  resources :salesmanagers
  resources :cars do
  member do
    get 'cost'
  end
end
  resources :owners
  resources :homes
  resources :abouts

  root 'homes#index'

end

app/models/quote.rb
class Quote < ActiveRecord::Base

  belongs_to :salesperson
  belongs_to :customer
  belongs_to :car


before_save :quote_check_sold


  def date_created_cannot_be_in_the_past
    errors.add(:date_created, "can't be in the past")if
        !date_created.blank? and date_created <Date.today
  end

  def self.sum_price
    Quote.where("date_sold IS NULL").sum(:price)
  end

  def self.sum_price_sold
    Quote.where("date_sold is not null").sum(:price)
  end

  def self.count_sold
    Quote.where("date_sold is not null").count(:price)
  end

  def self.quotes_by_salesperson
    Quote.sum(:price).group("salesperson_id")
  end

  def self.q_open
    where("date_sold is null")
  end

  def self.q_closed
    where("date_sold is not null")
  end

   def self.sum_salesperson_sold(salesperson_id)
       where("salesperson_id = ? AND date_sold is not null", salesperson_id ).sum(:price)
  end

  def quote_check_sold

    if unless self.date_sold.nil?
         car.update_column(:sold, true)
       end
    end
   end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]

  # GET /quotes
  # GET /quotes.json
  def index
  @quotes = Quote.all
  @all_quotes_count  = Quote.count
  @quotes_closed = Quote.q_closed
  @quotes_open = Quote.q_open
  @quote_count_sold = Quote.count_sold

end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:quote_number, :salesperson_id, :car_id, :customer_id, :price, :date_created, :date_sold)
    end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quote_number %><br>
    <%= f.text_field :quote_number %>
  </div>
  <div class="field">
    <%= f.label :salesperson_name %><br>
    <%= f.collection_select :salesperson_id, Salesperson.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :car_vin %><br>
    <%= f.collection_select :car_id, Car.car_available, :id, :vin %>
  </div>
  <div class="field">
    <%= f.label :customer_name %><br>
    <%= f.collection_select :customer_id, Customer.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>

   </div>
  <div class="field">
    <%= f.label :date_created %><br>
    <%= f.date_select :date_created %>
  </div>
  <div class="field">
    <%= f.label :date_sold %><br>
    <%= f.date_select :date_sold, :include_blank => true%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <h1>Open Quotes</h1>
  <thead>
    <tr>
      <th>Quote Number</th>
      <th>Sales Person</th>
      <th>Car</th>
      <th>Customer</th>
      <th>Price</th>
      <th>Date Created</th>
      <th>Date Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes_open.each do |quote| %>
      <tr>
        <td><%= quote.quote_number %></td>
        <td><%= quote.salesperson.name %></td>
        <td><%= quote.car.vin %></td>
        <td><%= quote.customer.name %></td>
        <td><%= number_to_currency(quote.price) %></td>
        <td><%= quote.date_created %></td>
        <td><%= quote.date_sold %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Delete', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>





    <table>
      <h1>Closed Quotes</h1>
      <thead>
      <tr>
        <th>Quote Number</th>
        <th>Sales Person</th>
        <th>Car</th>
        <th>Customer</th>
        <th>Price</th>
        <th>Date Created</th>
        <th>Date Sold</th>
        <th colspan="3"></th>
      </tr>
      </thead>

      <tbody>
      <% @quotes_closed.each do |quote| %>
          <tr>
            <td><%= quote.quote_number %></td>
            <td><%= quote.salesperson.name %></td>
            <td><%= quote.car.vin %></td>
            <td><%= quote.customer.name %></td>
            <td><%= number_to_currency(quote.price) %></td>
            <td><%= quote.date_created %></td>
            <td><%= quote.date_sold %></td>
            <td><%= link_to 'Show', quote %></td>
            <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
            <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
      <% end %>
  </tbody>
</table>
    <br>
    <br>
    <%= form_tag(cars_path, :method => "get", class: "navbar-form", id: "search-form") do %>
      <div class="input-append">
        <%= text_field_tag :search, params[:search], class: "span2", placeholder: "Search for cars" %>
        <!-- In order to have the "search" icon int the button, we need to use plain HTML instead
             of using a Rails form helper -->
        <button class="btn" type="submit"><i class="icon-search"></i></button>
      </div>
  <% end %>
<br>
<br>
<%= link_to 'New Quote', new_quote_path %>
<br>
<br>
<%= link_to 'Back', salespeople_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quote number:</strong>
  <%= @quote.quote_number %>
</p>

<p>
  <strong>Sales Person</strong>
  <%= @quote.salesperson.name %>
</p>

<p>
  <strong>Car:</strong>
  <%= @quote.car.vin %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @quote.customer.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@quote.price) %>
</p>

<p>
  <strong>Date created:</strong>
  <%= @quote.date_created %>
</p>

<p>
  <strong>Date sold:</strong>
  <%= @quote.date_sold %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>