config/routes.rb
Rails.application.routes.draw do

  resources :loans
  resources :quotes
  resources :customers
  resources :salespeople
  resources :salesmanagers
  resources :cars do
  member do
    get 'cost'
  end
end
  resources :owners
  resources :homes
  resources :abouts

  root 'homes#index'

end

app/controllers/salespeople_controller.rb
class SalespeopleController < ApplicationController
  before_action :set_salesperson, only: [:show, :edit, :update, :destroy]

  # GET /salespeople
  # GET /salespeople.json
  def index
    @salespeople = Salesperson.all

  end

  # GET /salespeople/1
  # GET /salespeople/1.json
  def show
  end

  # GET /salespeople/new
  def new
    @salesperson = Salesperson.new

  end

  # GET /salespeople/1/edit
  def edit
  end

  # POST /salespeople
  # POST /salespeople.json
  def create
    @salesperson = Salesperson.new(salesperson_params)

    respond_to do |format|
      if @salesperson.save
        format.html { redirect_to @salesperson, notice: 'Salesperson was successfully created.' }
        format.json { render :show, status: :created, location: @salesperson }
      else
        format.html { render :new }
        format.json { render json: @salesperson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salespeople/1
  # PATCH/PUT /salespeople/1.json
  def update
    respond_to do |format|
      if @salesperson.update(salesperson_params)
        format.html { redirect_to @salesperson, notice: 'Salesperson was successfully updated.' }
        format.json { render :show, status: :ok, location: @salesperson }
      else
        format.html { render :edit }
        format.json { render json: @salesperson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salespeople/1
  # DELETE /salespeople/1.json
  def destroy
    @salesperson.destroy
    respond_to do |format|
      format.html { redirect_to salespeople_url, notice: 'Salesperson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salesperson
      @salesperson = Salesperson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salesperson_params
      params.require(:salesperson).permit(:name, :phone, :salesmanager_id)
    end
end

app/helpers/salespeople_helper.rb
module SalespeopleHelper
end

app/views/salespeople/_form.html.erb
<%= form_for(@salesperson) do |f| %>
  <% if @salesperson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@salesperson.errors.count, "error") %> prohibited this salesperson from being saved:</h2>

      <ul>
      <% @salesperson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :salesmanager_name %><br>
    <%= f.collection_select :salesmanager_id, Salesmanager.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/salespeople/edit.html.erb
<h1>Editing Salesperson</h1>

<%= render 'form' %>

<%= link_to 'Show', @salesperson %> |
<%= link_to 'Back', salespeople_path %>

app/views/salespeople/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sales Staff</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Sales Manager</th>
      <th>Amount Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @salespeople.each do |salesperson| %>
      <tr>
        <td><%= salesperson.name %></td>
        <td><%= salesperson.phone %></td>
        <td><%= salesperson.salesmanager.name %></td>
        <td><%= number_to_currency(Quote.sum_salesperson_sold(salesperson.id)) %></td>
        <td><%= link_to 'Show', salesperson %></td>
        <td><%= link_to 'Edit', edit_salesperson_path(salesperson) %></td>
        <td><%= link_to 'Terminate', salesperson, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<br>
<br>
<%= form_tag(cars_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Cars" %>
    <%= submit_tag "Search" %>
<% end %>
<br>
<br>
<%= link_to 'Customers', customers_path %>
<br>
<br>
<%= link_to 'New Customer', new_customer_path %>
<br>
<br>
<%= link_to 'Quotes', quotes_path %>
<br>
<br>
<%= link_to 'New Quote', new_quote_path %>

app/views/salespeople/new.html.erb
<h1>New Salesperson</h1>

<%= render 'form' %>

<%= link_to 'Back', salespeople_path %>

app/views/salespeople/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @salesperson.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @salesperson.phone %>
</p>

<p>
  <strong>Salesmanager:</strong>
  <%= @salesperson.salesmanager.name %>
</p>

<%= link_to 'Edit', edit_salesperson_path(@salesperson) %> |
<%= link_to 'Back', salespeople_path %>