config/routes.rb
Rails.application.routes.draw do

  resources :loans
  resources :quotes
  resources :customers
  resources :salespeople
  resources :salesmanagers
  resources :cars do
  member do
    get 'cost'
  end
end
  resources :owners
  resources :homes
  resources :abouts

  root 'homes#index'

end

app/models/car.rb
class Car < ActiveRecord::Base

  belongs_to :quote

  validates :year, presence: true
  validates :make, presence: true
  validates :model, presence: true
  validates :vin, presence: true, uniqueness: true
  validates :color, presence: true

  def self.sum_cost
    Car.sum(:cost)
  end

  def self.sum_cost_sold
    Car.sum(:cost)
  end

  def self.car_available
   Car.where(sold:  false)
  end

  def self.car_sold
    where(sold:  true)
  end

  def self.search(search)
   where("make LIKE ? OR model LIKE ? OR vin LIKE ? OR color LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%","%#{search}%")
    # where("make LIKE ?","%#{search}%")
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    # @cars = Car.all
    Rails.logger.debug "Search params = #{params[:search]}"
    unless params[:search].nil?
      @cars = Car.search(params[:search]).order("created_at DESC")
      Rails.logger.debug @cars.inspect
    else
     @cars = Car.all.order("created_at DESC")
    end
      @car_sum_cost = Car.sum_cost
      @car_sum_cost_sold = Car.sum_cost_sold
      @car_available = Car.car_available
      @car_sold = Car.car_sold

   end

  def cost
   cost = Car.find(params[:id])
    render json: cost
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def car_sold
    :set_car
    sold=true
    update
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:year, :make, :model, :color, :vin, :cost, :sold)
    end


end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<%= debug(@cars) %>
<% if @cars %>

<% else %>
    <p>There are no Cars containing the term(s) <%= params[:search] %>.</p>
<% end %>

app/views/cars/_form.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br>
    <%= f.text_field :year %>
  </div>
  <div class="field">
    <%= f.label :make %><br>
    <%= f.text_field :make %>
  </div>
  <div class="field">
    <%= f.label :model %><br>
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :vin %><br>
    <%= f.text_field :vin %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :sold %><br>
    <%= f.check_box :sold %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Inventory Management</h1>
<br>
<br>
<h2>Search Cars By Make, Model, VIN or Color</h2>
<br>
<%= form_tag(cars_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Cars" %>
    <%= submit_tag "Search" %>
<% end %>
<br>
<br>
<br>
<table>

  <thead>
  <tr>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
    <th>Color</th>
    <th>Vin</th>
    <th>Cost</th>
    <th>Sold</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @cars.each do |car| %>
      <tr>
        <td><%= car.year %></td>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.vin %></td>
        <td><%= number_to_currency(car.cost) %></td>
        <td><%= car.sold %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<table>
  <br>
  <br>
  <h2>Cars Available for sale</h2>
  <thead>
    <tr>
      <th>Year</th>
      <th>Make</th>
      <th>Model</th>
      <th>Color</th>
      <th>Vin</th>
      <th>Cost</th>
      <th>Sold</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @car_available.each do |car| %>
      <tr>
        <td><%= car.year %></td>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.vin %></td>
        <td><%= number_to_currency(car.cost) %></td>
        <td><%= car.sold %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Remove', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<br>
<table>
  <h2>Cars that have been sold</h2>
  <thead>
  <tr>
    <th>Year</th>
    <th>Make</th>
    <th>Model</th>
    <th>Color</th>
    <th>Vin</th>
    <th>Cost</th>
    <th>Sold</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @car_sold.each do |car| %>
      <tr>
        <td><%= car.year %></td>
        <td><%= car.make %></td>
        <td><%= car.model %></td>
        <td><%= car.color %></td>
        <td><%= car.vin %></td>
        <td><%= number_to_currency(car.cost) %></td>
        <td><%= car.sold %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<br>

<br>
<br>

<%= link_to 'Add a New Car to inventory', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Make:</strong>
  <%= @car.make %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Vin:</strong>
  <%= @car.vin %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @car.cost %>
</p>

<p>
  <strong>Sold:</strong>
  <%= @car.sold %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>